"""
EXTERNAL AGENT PROTOCOL (EAP) - DTOs
Defines the schema for communication with external agents.
Follows ADR-001.
"""

from datetime import datetime, timezone
from enum import Enum
from typing import Dict, List, Any, Optional, Union
from uuid import UUID, uuid4

from pydantic import BaseModel, Field, ConfigDict, field_validator

from ...domain.entities.agent import AgentCapability, AgentType


class EAPStatus(str, Enum):
    """External agent health status"""
    HEALTHY = "healthy"
    DEGRADED = "degraded"
    BUSY = "busy"
    OFFLINE = "offline"


class EAPRegistrationRequest(BaseModel):
    """
    Agent Registration Payload
    Sent by external agent to orchestrator.
    """
    protocol_version: str = Field(default="1.0")
    name: str = Field(..., min_length=3, max_length=100, pattern=r"^[A-Z0-9_\-]+$")
    version: str = Field(default="1.0.0")
    agent_type: AgentType = Field(default=AgentType.IMPLEMENTER)
    capabilities: List[AgentCapability]
    endpoint_url: Optional[str] = Field(None, description="Webhook URL if push-based")
    metadata: Dict[str, Any] = Field(default_factory=dict)
    
    model_config = ConfigDict(extra="ignore")


class EAPRegistrationResponse(BaseModel):
    """
    Response to registration.
    Includes the assigned Agent ID and authentication token.
    """
    agent_id: UUID
    status: str = "registered"
    auth_token: str = Field(..., description="Token for future requests")
    heartbeat_interval_seconds: int = 30
    
    model_config = ConfigDict(from_attributes=True)


class EAPHeartbeatRequest(BaseModel):
    """
    Periodic heartbeat from agent.
    """
    status: EAPStatus
    current_load: float = Field(0.0, ge=0.0, le=1.0)
    tasks_in_progress: int = 0
    metrics: Dict[str, Any] = Field(default_factory=dict)
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    
    model_config = ConfigDict(arbitrary_types_allowed=True)


class EAPTaskAssignment(BaseModel):
    """
    Task payload sent TO the external agent.
    """
    task_id: UUID
    session_id: UUID
    task_type: str
    context: Dict[str, Any]
    input_data: str
    requirements: List[str] = Field(default_factory=list)
    timeout_seconds: int = 3600
    
    model_config = ConfigDict(arbitrary_types_allowed=True)


class EAPTaskArtifact(BaseModel):
    """File or data generated by the task"""
    path: str
    content: str
    mime_type: str = "text/plain"


class EAPTaskResult(BaseModel):
    """
    Result payload sent FROM the external agent.
    """
    task_id: UUID
    status: str = Field(..., pattern="^(completed|failed)$")
    artifacts: List[EAPTaskArtifact] = Field(default_factory=list)
    output_data: Optional[Dict[str, Any]] = None
    error_message: Optional[str] = None
    
    # Execution Metrics
    execution_time_ms: float = 0.0
    tokens_used: int = 0
    cost_usd: float = 0.0
    
    model_config = ConfigDict(arbitrary_types_allowed=True)
